USE [master]
GO
/****** Object:  Database [info]    Script Date: 9/25/2020 2:09:45 PM ******/
CREATE DATABASE [info]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'info', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MESQL\MSSQL\DATA\info.mdf' , SIZE = 466944KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'info_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MESQL\MSSQL\DATA\info_log.ldf' , SIZE = 335872KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [info].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [info] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [info] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [info] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [info] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [info] SET ARITHABORT OFF 
GO
ALTER DATABASE [info] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [info] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [info] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [info] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [info] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [info] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [info] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [info] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [info] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [info] SET  DISABLE_BROKER 
GO
ALTER DATABASE [info] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [info] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [info] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [info] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [info] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [info] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [info] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [info] SET RECOVERY FULL 
GO
ALTER DATABASE [info] SET  MULTI_USER 
GO
ALTER DATABASE [info] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [info] SET DB_CHAINING OFF 
GO
ALTER DATABASE [info] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [info] SET TARGET_RECOVERY_TIME = 60 SECONDS 
	GO
	ALTER DATABASE [info] SET DELAYED_DURABILITY = DISABLED 
	GO
	EXEC sys.sp_db_vardecimal_storage_format N'verify-aio', N'ON'
	GO
	USE [info]
	GO

--
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE TABLE [dbo].[Email](
		[id] [int] NOT NULL,
		[email] [varchar](64) NULL,
		[level] [varchar](64) NULL,
		[subject] [nvarchar](64) NULL,
		[data] [nvarchar](64) NULL
	PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO

	--------------------
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE TABLE [dbo].[Message](
		[id] [int] NOT NULL,
		[phone_number] [varchar](15) NULL,
		[level] [varchar](64) NULL,
		[data] [nvarchar](64) NULL
	PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO

	--
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE TABLE [dbo].[Log](
		[id] [int] NOT NULL,
		[code] [varchar](10) NULL,
		[name] [varchar](24) NULL
	PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO

	-----------------------
	INSERT [dbo].[Log] ([id], [code], [name]) VALUES (1, N'0', N'Emergency')
	INSERT [dbo].[Log] ([id], [code], [name]) VALUES (2, N'1', N'Alert')
	INSERT [dbo].[Log] ([id], [code], [name]) VALUES (3, N'2', N'Critical')
	INSERT [dbo].[Log] ([id], [code], [name]) VALUES (4, N'3', N'Error')
	INSERT [dbo].[Log] ([id], [code], [name]) VALUES (5, N'4', N'Warning')
	INSERT [dbo].[Log] ([id], [code], [name]) VALUES (6, N'5', N'Notification')
	INSERT [dbo].[Log] ([id], [code], [name]) VALUES (7, N'6', N'Informational')
	INSERT [dbo].[Log] ([id], [code], [name]) VALUES (8, N'7', N'Debugging')
	

